# vscode needs the cargo in the root
# You can run a sub project with $cargo run -p leet

[workspace]

members = [
  "rust/control-flow",
  "rust/enums",
  "rust/human-struct",
  "rust/ownership",
  "rust/leet",
]
