# vscode needs the cargo in the root
# You can run a sub project with $cargo run -p leet

[workspace]
resolver = "2"

members = [
  "exploration/control-flow",
  "exploration/enums",
  "exploration/human-struct",
  "exploration/ownership",
  "exploration/leet",
]
